### ISSUE TITLE
Computational Law Journal 

### ISSUE THREAD

**Issue by dazzaji** [mitmedialab/2019-MIT-Computational-Law-Course#14]
Draft initial article: https://hackmd.io/cY_eZ5x2TiOVl2CpOj88rg

**Comment by MilaRioja** [comment]
Could we express "Legal Practice as Applied Information Science" as _Legal Practice Enhanced by Technology as Applied Information Science"_?

**Comment by dazzaji** [comment]
Good point.  This bullet should probably be pulled from the attempt at describing layers of a stack (or facets of a computational field) and instead be posed as the goal or end result of what we can have and be when all that is achieved.

**Comment by dazzaji** [comment]
Here is some placeholder language from the front page that needs to be replaced: 

"The MIT Computational Law Journal generates, fosters and propagates public ideas around open technology. Our purpose is to transform law for the digital age. We publish Essays, Articles, Comments and Events taking place at the intersection of law and technology. We believe in providing innovative content that is freely available to all those who are interested. 

Law is the scaffolding that enables social order and change. Which is why it’s critical that law keeps up with the increasing speed that technology is developing. In order to ensure that high-quality content is being published, the journal is edited by a distinguished editorial board of MIT and MIT-affiliated practitioners based out of the MIT Media Lab."

**Comment by dazzaji** [comment]
The rough outline is now online at: https://computationallaw.pubpub.org . It's up to MIT what/when/how to roll out next steps.  This issue is therefore closed.
